######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 27 23:43:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++0x
# Input
HEADERS += andgate.h gatebase.h logicsimplifier.h mainwindow.h orgate.h \
    input.h \
    circuitline.h \
    equationeditor.h \
    karnaugh.h
FORMS += mainwindow.ui
SOURCES += andgate.cpp \
           gatebase.cpp \
           logicsimplifier.cpp \
           main.cpp \
           mainwindow.cpp \
           orgate.cpp \
    input.cpp \
    circuitline.cpp \
    equationeditor.cpp \
    karnaugh.cpp

RESOURCES += \
    ressources.qrc
