######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 27 23:43:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += andgate.h gatebase.h logicsimplifier.h mainwindow.h orgate.h \
    input.h
FORMS += mainwindow.ui
SOURCES += andgate.cpp \
           gatebase.cpp \
           logicsimplifier.cpp \
           main.cpp \
           mainwindow.cpp \
           orgate.cpp \
    input.cpp
